global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gems-lms
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080
          - ms-auth:8081
          - ms-admin:8082
          - ms-education:8083
